apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: food-microservices-payment-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: stripe-secret
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3003"
            - name: FRONTEND_URL
              value: "http://localhost:5173"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: food-app
spec:
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP